server:
  port: 7000
spring:
  application:
    name: erueka-server

eureka:
  instance:
    hostname:
      eureka-server7000

  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server7001/eureka/
