
server:
  port: 7002
spring:
  application:
    name: erueka-server

eureka:
  instance:
    hostname:
      eureka-server2

  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server1:7001/eureka/