server:
  port: 7001
spring:
  application:
    name: erueka-server

eureka:
  instance:
    hostname:
      eureka-server1

  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server2:7002/eureka/