spring:
  datasource:
    url: jdbc:mysql://rm-bp1f17x0sw34c4avc4o.mysql.rds.aliyuncs.com:3306/smbms?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: admin_test
    password: QAZwsx!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
